name: application_1
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  device_info_fetcher:
  log_db_package:
  pax_api_plugin:
  scotch_dev_error:
  sqlite_postgresql_connector:
  yaml_parser_fetcher:
  audit_db_package:
  cupertino_icons: ^1.0.6

dependency_overrides:

  shared_database:
    path: ../shared_database

  device_info_fetcher:
    git:
      url: https://github.com/Flutter-Apps-pty/scotch_software.git
      path: packages/utils/device_info_fetcher


  pax_api_plugin:
    git:
      url: https://github.com/Flutter-Apps-pty/scotch_software.git
      path: packages/pax/pax_api_plugin

  scotch_dev_error:
    git:
      url: https://github.com/Flutter-Apps-pty/scotch_software.git
      path: packages/utils/scotch_dev_error


  sqlite_postgresql_connector:
    git:
      url: https://github.com/Flutter-Apps-pty/scotch_software.git
      path: packages/databases/sqlite_postgresql_connector
  log_db_package:
    git:
      url: https://github.com/Flutter-Apps-pty/scotch_software.git
      path: packages/databases/log_db_package
  yaml_parser_fetcher:
    git:
      url: https://github.com/Flutter-Apps-pty/scotch_software.git
      path: packages/utils/yaml_parser_fetcher

  audit_db_package:
    git:
      url: https://github.com/Flutter-Apps-pty/scotch_software.git
      path: packages/databases/audit_db_package



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true

